### ISSUE TITLE
How do I know the number of new additions when the screen is not scrolling.

### ISSUE THREAD

**Issue by wuweijian1997** [SimonWang9610/indexed_scroll_observer#14]
I am using `PositionRetainedScrollPhysics` in a chat list. When I swipe up, if there are new messages, the screen will not scroll, but I want to know how many new messages there are and display the number of unread messages.

**Comment by wuweijian1997** [comment]
Like this. I want to get the number of unread new messages
![1](https://github.com/user-attachments/assets/493d2484-2228-434e-b4ad-90fcb6acd26b)

**Comment by SimonWang9610** [comment]
@wuweijian1997 

2 possible solutions.

Solution 1: (you maintain two message lists, one for read, and another for unread) 
When users scroll up, all incoming messages can be put into the unread message list to show the exact unread count. Typically, the two message lists should be shown in two sliver lists of the same `CustomScrollView`

Solution 2: 
using `ObserverProxy` to wrap each message card to monitor the index change of visible messages in the scroll list. Then, you can check if the index (unread new message) is visible in the scroll list.
